{{ if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "brigade.api.fullname" . }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    role: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.externalPort }}
    targetPort: {{ .Values.api.service.internalPort }}
    protocol: TCP
    name: {{ .Values.api.service.name }}
  selector:
    app.kubernetes.io/name: {{ template "brigade.api.fullname" . }}
{{ end }}
