apiVersion: v1
appVersion: v0.20.0
deprecated: true
description: The legacy OAuth GitHub Gateway for Brigade
name: brigade-github-oauth
sources:
- https://github.com/brigadecore/github-gateway-oauth
version: 0.3.0
